### ISSUE TITLE
Implementation in Neural Networks

### ISSUE THREAD

**Issue by javej** [nathanrooy/Particle-Swarm-Optimization-with-Python#2]
Good day, Mr. Roy. I would just like to ask if how could I implement PSO in the improvement of a neural networks' weights? I've read a lot about using PSO to optimize the weights during the training phase of the neural networks but I haven't seen an implementation of how to do it in Python. Any help will be so much appreciated. Hoping for your kind response. Thank you.

**Comment by nathanrooy** [comment]
It depends on what kind of network you're dealing with. If it's just a simple MLP, swapping out back propagation for PSO is trivial. Simply use the networks weight matrix as your optimization inputs and the cost function becomes the network error.
