### ISSUE TITLE
Sorry I am unable to understand your cost function, Please tell First what is your cost function (in mathematical form) ? and Second, I want to put my own cost function in the program where should I make changes and how??

### ISSUE THREAD

**Issue by sunitachaurasia** [nathanrooy/Particle-Swarm-Optimization-with-Python#6]

**Comment by hormone03** [comment]
His cost function is the sum of the squares of the positional coordinates of the particle, say f(x,y).
Which means f(x,y)=total = x^2 + y^2
And if you want to use your own cost function, just edit the cost_functions.py to fit yours. 
Or simply define your own cost function directly as an equation.
